### ISSUE TITLE
Getting need at least one array to stack at run.sh line 121

### ISSUE THREAD

**Issue by localhost-server** [eth-ait/GaussianHaircut#12]
Hi, I have been facing this issue, i got the model trained but after that i am facing this.
CUDA_VISIBLE_DEVICES="$GPU" python fit.py --conf confs/train_person_1.conf \
>     --batch_size 1 --train_rotation True --fixed_images True \
>     --save_path $DATA_PATH/flame_fitting/$EXP_NAME_1/stage_1 \
>     --data_path $DATA_PATH \
>     --fitted_camera_path $EXP_PATH_1/cameras/30000_matrices.pkl
creating the SMPLX Decoder
Overwriting COLMAP cameras with optimized cameras
Traceback (most recent call last):
  File "/home/lab/Desktop/GaussianHaircut/ext/NeuralHaircut/src/multiview_optimization/fit.py", line 82, in <module>
    main(
  File "/home/lab/Desktop/GaussianHaircut/ext/NeuralHaircut/src/multiview_optimization/fit.py", line 24, in main
    dataset = Multiview_dataset(data_path, fitted_camera_path, use_scale, fixed_images, **conf['dataset'], device=conf['general.device'], batch_size=batch_size)
  File "/home/lab/Desktop/GaussianHaircut/ext/NeuralHaircut/src/multiview_optimization/dataset/dataset.py", line 162, in __init__
    self.lmks = torch.from_numpy(np.stack([lmks[i] for i in self.good_views]))
  File "<__array_function__ internals>", line 200, in stack
  File "/home/lab/miniconda3/envs/gaussian_splatting_hair/lib/python3.9/site-packages/numpy/core/shape_base.py", line 460, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

**Comment by travellerCh** [comment]
Hello, I ran into the same error. Have you solved it? Could you please share your solution?
