### ISSUE TITLE
Example video

### ISSUE THREAD

**Issue by autolife-nz** [eth-ait/GaussianHaircut#13]
Hello,

Thanks for making this code available - amazing work. We are currently trying to debug our installation but are having difficulty knowing if errors are from config, or from the input video file that we recorded ourselves. It would be very helpful to have one input video that we know works,  so we can rule out input data as a cause of the errors. Would it be possible to release one of the example videos on the project page? 

Many thanks.

**Comment by snow-nene** [comment]
> Hello,
> 
> Thanks for making this code available - amazing work. We are currently trying to debug our installation but are having difficulty knowing if errors are from config, or from the input video file that we recorded ourselves. It would be very helpful to have one input video that we know works, so we can rule out input data as a cause of the errors. Would it be possible to release one of the example videos on the project page?
> 
> Many thanks.

Yes, I am encountering the same problem now.

**Comment by canyueduhong** [comment]
Yes, I am encountering the same problem now. The error is reported as follows

[ITER 30000] Saving Checkpoint [08/11 16:26:44]

Training complete. [08/11 16:26:45]
creating the SMPLX Decoder
Data path: /home/tom/fssd/GaussianHaircut/scene/folder
Fitted camera path: /home/tom/fssd/GaussianHaircut/scene/folder/3d_gaussian_splatting/stage1/cameras/30000_matrices.pkl
Overwriting COLMAP cameras with optimized cameras
Traceback (most recent call last):
  File "/home/tom/fssd/GaussianHaircut/ext/NeuralHaircut/src/multiview_optimization/fit.py", line 83, in <module>
    main(
  File "/home/tom/fssd/GaussianHaircut/ext/NeuralHaircut/src/multiview_optimization/fit.py", line 25, in main
    dataset = Multiview_dataset(data_path, fitted_camera_path, use_scale, fixed_images, **conf['dataset'], device=conf['general.device'], batch_size=batch_size)
  File "/home/tom/fssd/GaussianHaircut/ext/NeuralHaircut/src/multiview_optimization/dataset/dataset.py", line 162, in __init__
    self.lmks = torch.from_numpy(np.stack([lmks[i] for i in self.good_views]))
  File "<__array_function__ internals>", line 200, in stack
  File "/opt/conda/envs/gaussian_splatting_hair/lib/python3.9/site-packages/numpy/core/shape_base.py", line 460, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

**Comment by autolife-nz** [comment]
Hello

Yes we are stuck on the same issue 'ValueError('need at least one array to
stack')', and not sure if it's a config/code issues,  or data issue.

Please email me at ***@***.*** and we can share any progress we
make.

**Comment by canyueduhong** [comment]
Okay, but your email is hidden

**Comment by autolife-nz** [comment]
Check our github profile (make sure you are logged in) and you should see
my email address in profile. Seems Github removes emails in messages

**Comment by canyueduhong** [comment]
ok i see

**Comment by canyueduhong** [comment]
Brother, I found out what the problem is. The problem is that when filtering high-quality pictures, setting it to 0.6, which causes no one to filter and the array is empty. Just change it to a lower level.

![image](https://github.com/user-attachments/assets/b0d8c351-e673-48e3-8d0e-2866d493e369)

**Comment by autolife-nz** [comment]
Will try tomorrow. Thank you!

**Comment by autolife-nz** [comment]
![image](https://github.com/user-attachments/assets/ebb4f523-8946-433f-9f94-9d4e546c96c6)
Hello, we changed if score > 0.2 to 0.2, 0.1, 0.0 but we are still having the same problem. Did you get the whole process to work? Did you managed to get a final output?  Also will send you a email. Thanks.

**Comment by canyueduhong** [comment]
I have resolved the “need at least one array to stack” issue. However, as it was the weekend, I haven’t completed the full pipeline yet. So far, I have successfully run the RECONSTRUCTION part of the .run.sh script. I am currently working on the subsequent steps, and I will share the results with you via email once they are ready.
I have sent the video to your email. I hope it helps you resolve the issue. Keep up the great work, and best of luck!

**Comment by canyueduhong** [comment]
I have successfully obtained the final result. We can continue our communication via email.

**Comment by kevinu0628** [comment]
Hello, I encountered issues generating the final output results through the current implementation. Could you please share a reference input video file that is known to produce correct results in your testing environment?
