### ISSUE TITLE
Hello author, I am running run.sh and reported the following error. Is there a solution for this? The environment is set up

### ISSUE THREAD

**Issue by canyueduhong** [eth-ait/GaussianHaircut#15]
(base) tom@premium-stratosphere-4990-85dc5964d5-rzblm:~/fssd/GaussianHaircut$ ./run.sh 
Traceback (most recent call last):
  File "demos/demo_fit_face.py", line 3, in <module>
    import torch.backends.cudnn as cudnn
  File "/opt/conda/envs/pixie-env/lib/python3.8/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: /opt/conda/envs/pixie-env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent

**Comment by canyueduhong** [comment]
The problem is solved!
