### ISSUE TITLE
Issue executing the project

### ISSUE THREAD

**Issue by RichardBaoRepo** [eth-ait/GaussianHaircut#16]
I ran into the following error while running it. i tried install some of the module in conda environment, but some module like diff_gaussian_rasterization, simple_knn were custom module. i am not sure where i did it wrong. any suggestions would be appreciate~

`/home/nio/miniforge3/envs/pixie-env/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/nio/miniforge3/envs/pixie-env/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
total 128 images
Traceback (most recent call last):
  File "demos/demo_fit_face.py", line 133, in <module>
    main(parser.parse_args())
  File "demos/demo_fit_face.py", line 30, in main
    testdata = TestData(args.inputpath, iscrop=args.iscrop)
  File "/home/nio/Projects/GaussianHaircut/ext/PIXIE/pixielib/datasets/face_datasets.py", line 54, in __init__
    self.face_detector = detectors.FAN()
  File "/home/nio/Projects/GaussianHaircut/ext/PIXIE/pixielib/datasets/detectors.py", line 145, in __init__
    self.model = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False)
  File "/home/nio/miniforge3/envs/pixie-env/lib/python3.8/enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/nio/Projects/GaussianHaircut/src/train_gaussians.py", line 18, in <module>
    from gaussian_renderer import render, network_gui
  File "/home/nio/Projects/GaussianHaircut/src/gaussian_renderer/__init__.py", line 15, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'
creating the SMPLX Decoder
Traceback (most recent call last):
  File "/home/nio/Projects/GaussianHaircut/ext/NeuralHaircut/src/multiview_optimization/fit.py", line 82, in <module>
    main(
  File "/home/nio/Projects/GaussianHaircut/ext/NeuralHaircut/src/multiview_optimization/fit.py", line 24, in main
    dataset = Multiview_dataset(data_path, fitted_camera_path, use_scale, fixed_images, **conf['dataset'], device=conf['general.device'], batch_size=batch_size)
  File "/home/nio/Projects/GaussianHaircut/ext/NeuralHaircut/src/multiview_optimization/dataset/dataset.py", line 60, in __init__
    world_mats_dict = pickle.load(open(fitted_camera_path, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/nio/Projects/scene/3d_gaussian_splatting/stage1/cameras/30000_matrices.pkl'
creating the SMPLX Decoder
Traceback (most recent call last):
  File "/home/nio/Projects/GaussianHaircut/ext/NeuralHaircut/src/multiview_optimization/fit.py", line 82, in <module>
    main(
  File "/home/nio/Projects/GaussianHaircut/ext/NeuralHaircut/src/multiview_optimization/fit.py", line 24, in main
    dataset = Multiview_dataset(data_path, fitted_camera_path, use_scale, fixed_images, **conf['dataset'], device=conf['general.device'], batch_size=batch_size)
  File "/home/nio/Projects/GaussianHaircut/ext/NeuralHaircut/src/multiview_optimization/dataset/dataset.py", line 60, in __init__
    world_mats_dict = pickle.load(open(fitted_camera_path, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/nio/Projects/scene/3d_gaussian_splatting/stage1/cameras/30000_matrices.pkl'
creating the SMPLX Decoder
Traceback (most recent call last):
  File "/home/nio/Projects/GaussianHaircut/ext/NeuralHaircut/src/multiview_optimization/fit.py", line 82, in <module>
    main(
  File "/home/nio/Projects/GaussianHaircut/ext/NeuralHaircut/src/multiview_optimization/fit.py", line 24, in main
    dataset = Multiview_dataset(data_path, fitted_camera_path, use_scale, fixed_images, **conf['dataset'], device=conf['general.device'], batch_size=batch_size)
  File "/home/nio/Projects/GaussianHaircut/ext/NeuralHaircut/src/multiview_optimization/dataset/dataset.py", line 60, in __init__
    world_mats_dict = pickle.load(open(fitted_camera_path, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/nio/Projects/scene/3d_gaussian_splatting/stage1/cameras/30000_matrices.pkl'
Traceback (most recent call last):
  File "/home/nio/Projects/GaussianHaircut/src/preprocessing/scale_scene_into_sphere.py", line 14, in <module>
    from gaussian_renderer import GaussianModel
  File "/home/nio/Projects/GaussianHaircut/src/preprocessing/../gaussian_renderer/__init__.py", line 15, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'
Traceback (most recent call last):
  File "/home/nio/Projects/GaussianHaircut/src/preprocessing/filter_flame_intersections.py", line 13, in <module>
    from gaussian_renderer import GaussianModel
  File "/home/nio/Projects/GaussianHaircut/src/preprocessing/../gaussian_renderer/__init__.py", line 15, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'
Traceback (most recent call last):
  File "/home/nio/Projects/GaussianHaircut/src/render_gaussians.py", line 14, in <module>
    from scene import Scene
  File "/home/nio/Projects/GaussianHaircut/src/scene/__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "/home/nio/Projects/GaussianHaircut/src/scene/dataset_readers.py", line 24, in <module>
    from scene.gaussian_model import BasicPointCloud
  File "/home/nio/Projects/GaussianHaircut/src/scene/gaussian_model.py", line 21, in <module>
    from simple_knn._C import distCUDA2
ModuleNotFoundError: No module named 'simple_knn'
Traceback (most recent call last):
  File "/home/nio/Projects/GaussianHaircut/src/preprocessing/extract_non_visible_head_scalp.py", line 20, in <module>
    from src.models.dataset import Dataset, MonocularDataset
  File "/home/nio/Projects/GaussianHaircut/src/preprocessing/../../ext/NeuralHaircut/src/models/dataset.py", line 21, in <module>
    from NeuS.models.dataset import load_K_Rt_from_P
ModuleNotFoundError: No module named 'NeuS.models'
Traceback (most recent call last):
  File "/home/nio/Projects/GaussianHaircut/src/train_latent_strands.py", line 18, in <module>
    from gaussian_renderer import render_hair, network_gui
  File "/home/nio/Projects/GaussianHaircut/src/gaussian_renderer/__init__.py", line 15, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'
Traceback (most recent call last):
  File "/home/nio/Projects/GaussianHaircut/src/train_strands.py", line 18, in <module>
    from gaussian_renderer import render_hair, network_gui
  File "/home/nio/Projects/GaussianHaircut/src/gaussian_renderer/__init__.py", line 15, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'
Traceback (most recent call last):
  File "/home/nio/Projects/GaussianHaircut/src/preprocessing/export_curves.py", line 10, in <module>
    from src.hair_networks.optimizable_textured_strands import OptimizableTexturedStrands
  File "/home/nio/Projects/GaussianHaircut/src/preprocessing/../../ext/NeuralHaircut/src/hair_networks/optimizable_textured_strands.py", line 28, in <module>
    from k_diffusion import config 
ModuleNotFoundError: No module named 'k_diffusion'
Traceback (most recent call last):
  File "/home/nio/Projects/GaussianHaircut/src/postprocessing/render_video.py", line 231, in <module>
    main(args.blender_path, args.input_path, args.exp_name_1, args.exp_name_3, args.strand_length, args.speed_up, args.max_frames)
  File "/home/nio/Projects/GaussianHaircut/src/postprocessing/render_video.py", line 114, in main
    cameras = pkl.load(open(f'{input_path}/3d_gaussian_splatting/{exp_name_1}/cameras/30000_matrices.pkl', 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/nio/Projects/scene/3d_gaussian_splatting/stage1/cameras/30000_matrices.pkl'
Traceback (most recent call last):
  File "/home/nio/Projects/GaussianHaircut/src/render_strands.py", line 14, in <module>
    from scene import Scene
  File "/home/nio/Projects/GaussianHaircut/src/scene/__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "/home/nio/Projects/GaussianHaircut/src/scene/dataset_readers.py", line 24, in <module>
    from scene.gaussian_model import BasicPointCloud
  File "/home/nio/Projects/GaussianHaircut/src/scene/gaussian_model.py", line 21, in <module>
    from simple_knn._C import distCUDA2
ModuleNotFoundError: No module named 'simple_knn'
ffmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.3.0 (conda-forge gcc 13.3.0-1)
  configuration: --prefix=/home/nio/miniforge3/envs/gaussian_splatting_hair --cc=/home/conda/feedstock_root/build_artifacts/ffmpeg_1730671401554/_build_env/bin/x86_64-conda-linux-gnu-cc --cxx=/home/conda/feedstock_root/build_artifacts/ffmpeg_1730671401554/_build_env/bin/x86_64-conda-linux-gnu-c++ --nm=/home/conda/feedstock_root/build_artifacts/ffmpeg_1730671401554/_build_env/bin/x86_64-conda-linux-gnu-nm --ar=/home/conda/feedstock_root/build_artifacts/ffmpeg_1730671401554/_build_env/bin/x86_64-conda-linux-gnu-ar --disable-doc --enable-openssl --enable-demuxer=dash --enable-hardcoded-tables --enable-libfreetype --enable-libharfbuzz --enable-libfontconfig --enable-libopenh264 --enable-libdav1d --disable-gnutls --enable-libmp3lame --enable-libvpx --enable-libass --enable-pthreads --enable-vaapi --enable-libopenvino --enable-gpl --enable-libx264 --enable-libx265 --enable-libaom --enable-libsvtav1 --enable-libxml2 --enable-pic --enable-shared --disable-static --enable-version3 --enable-zlib --enable-libopus --enable-librsvg --pkg-config=/home/conda/feedstock_root/build_artifacts/ffmpeg_1730671401554/_build_env/bin/pkg-config
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/nio/Projects/scene/raw.mp4':
  Metadata:
    major_brand     : qt  
    minor_version   : 512
    compatible_brands: qt  
    creation_time   : 2024-11-13T03:24:14Z
    encoder         : Lavf57.71.100
  Duration: 00:00:15.03, start: 0.000000, bitrate: 2988 kb/s
  Stream #0:0[0x1](eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720, 2853 kb/s, 30 fps, 30 tbr, 1000k tbn (default)
      Metadata:
        creation_time   : 2024-11-13T03:24:14.000000Z
        handler_name    : VideoHandler
        vendor_id       : FFMP
      Side data:
        displaymatrix: rotation of -90.00 degrees
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
      Metadata:
        creation_time   : 2024-11-13T03:24:14.000000Z
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/home/nio/Projects/scene/curves_reconstruction/stage3/raw_frames/%06d.jpg':
  Metadata:
    major_brand     : qt  
    minor_version   : 512
    compatible_brands: qt  
    encoder         : Lavf61.7.100
  Stream #0:0(eng): Video: mjpeg, yuv420p(pc, bt709, progressive), 720x1280, q=2-31, 200 kb/s, 30 fps, 30 tbn (default)
      Metadata:
        creation_time   : 2024-11-13T03:24:14.000000Z
        handler_name    : VideoHandler
        vendor_id       : FFMP
        encoder         : Lavc61.19.100 mjpeg
      Side data:
        cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: N/A
[out#0/image2 @ 0x55a475e42cc0] video:41757KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
frame=  451 fps=0.0 q=2.0 Lsize=N/A time=00:00:15.03 bitrate=N/A speed=70.2x    
Traceback (most recent call last):
  File "/home/nio/Projects/GaussianHaircut/src/postprocessing/concat_video.py", line 55, in <module>
    main(args.input_path, args.exp_name_3)
  File "/home/nio/Projects/GaussianHaircut/src/postprocessing/concat_video.py", line 24, in main
    img_names = sorted(os.listdir(f'{input_path}/curves_reconstruction/{exp_name_3}/train/ours_30000/renders'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/nio/Projects/scene/curves_reconstruction/stage3/train/ours_30000/renders'
`

**Comment by nebis-software** [comment]
same here.... did you solve somehow?
