### ISSUE TITLE
GaussianRasterizer.forward() unexpected keyword argument 'conic_precomp'

### ISSUE THREAD

**Issue by Theo-SAMINADIN-td** [eth-ait/GaussianHaircut#18]
Hi! When running run.sh, I've got several errors but I got stuck with the following one.

At this step :
 ```
# Run 3D Gaussian Splatting reconstruction
conda activate gaussian_splatting_hair && cd $PROJECT_DIR/src
CUDA_VISIBLE_DEVICES="$GPU" python train_gaussians.py \
    -s $DATA_PATH -m "$EXP_PATH_1" -r 1 --port "888$GPU" \
    --trainable_cameras --trainable_intrinsics --use_barf \
    --lambda_dorient 0.1
 ```

It returns :
```
(gaussian_splatting_hair) theo@theo-Linux:~/Documents/GH/GaussianHaircut/src$ CUDA_VISIBLE_DEVICES="$GPU" python train_gaussians.py     -s $DATA_PATH -m "$EXP_PATH_1" -r 1 --port "888$GPU"     --trainable_cameras --trainable_intrinsics --use_barf     --lambda_dorient 0.1
Optimizing /home/theo/Downloads//3d_gaussian_splatting/stage1
Output folder: /home/theo/Downloads//3d_gaussian_splatting/stage1 [18/11 06:56:27]
Reading camera 352/352 [18/11 06:56:27]
Loading Training Cameras [18/11 06:56:27]
100%|████████████████████████████████████████████████████████████| 352/352 [00:02<00:00, 152.59it/s]
Loading Test Cameras [18/11 06:56:29]
0it [00:00, ?it/s]
Number of points at initialisation :  14510 [18/11 06:56:29]
Training progress:   0%|                                                  | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/theo/Documents/GH/GaussianHaircut/src/train_gaussians.py", line 321, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/home/theo/Documents/GH/GaussianHaircut/src/train_gaussians.py", line 110, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background)
  File "/home/theo/Documents/GH/GaussianHaircut/src/gaussian_renderer/__init__.py", line 86, in render
    renders, _radii = rasterizer(
  File "/home/theo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: GaussianRasterizer.forward() got an unexpected keyword argument 'conic_precomp'
```

I can't figure out where it's coming from. Any help would be really appreciated :pray: 

- Ubuntu 22.04.5 LTS

**Comment by LarkLeeOnePiece** [comment]
Hello, did you solve it? I met the same problem...
