### ISSUE TITLE
About the Demo Data

### ISSUE THREAD

**Issue by fdyuandong** [eth-ait/GaussianHaircut#8]
Great work! Due to the complexity of the overall runtime environment, could you please provide a demo data along with the intermediate results? Thank you very much!

**Comment by egorzakharov** [comment]
Yes, we're trying to work out which demo data we can publish and how

**Comment by fdyuandong** [comment]
I’m looking forward to you releasing the demo data!

**Comment by snow-nene** [comment]
> Yes, we're trying to work out which demo data we can publish and how

`I20241027 10:03:24.126905 139823641604096 incremental_mapper.cc:378] => Image sees 1876 / 2744 points I20241027 10:03:24.996936 139823641604096 incremental_mapper.cc:41] Retriangulation and Global bundle adjustment         W20241027 10:03:58.655370 139823641604096 levenberg_marquardt_strategy.cc:123] Linear solver failure. Failed to compute a step: CHOLMOD warning: Matrix not positive definite. W20241027 10:04:01.479920 139823641604096 levenberg_marquardt_strategy.cc:123] Linear solver failure. Failed to compute a step: CHOLMOD warning: Matrix not positive definite. W20241027 10:04:07.657245 139823641604096 levenberg_marquardt_strategy.cc:123] Linear solver failure. Failed to compute a step: CHOLMOD warning: Matrix not positive definite. W20241027 10:04:13.775213 139823641604096 levenberg_marquardt_strategy.cc:123] Linear solver failure. Failed to compute a step: CHOLMOD warning: Matrix not positive definite.`

I crop your video on youtube as the demo data , and it has errors. I was wondering if there is any requirement to the video? such as resolution?

**Comment by RichardBaoRepo** [comment]
> > Yes, we're trying to work out which demo data we can publish and how
> 
> `I20241027 10:03:24.126905 139823641604096 incremental_mapper.cc:378] => Image sees 1876 / 2744 points I20241027 10:03:24.996936 139823641604096 incremental_mapper.cc:41] Retriangulation and Global bundle adjustment W20241027 10:03:58.655370 139823641604096 levenberg_marquardt_strategy.cc:123] Linear solver failure. Failed to compute a step: CHOLMOD warning: Matrix not positive definite. W20241027 10:04:01.479920 139823641604096 levenberg_marquardt_strategy.cc:123] Linear solver failure. Failed to compute a step: CHOLMOD warning: Matrix not positive definite. W20241027 10:04:07.657245 139823641604096 levenberg_marquardt_strategy.cc:123] Linear solver failure. Failed to compute a step: CHOLMOD warning: Matrix not positive definite. W20241027 10:04:13.775213 139823641604096 levenberg_marquardt_strategy.cc:123] Linear solver failure. Failed to compute a step: CHOLMOD warning: Matrix not positive definite.`
> 
> I crop your video on youtube as the demo data , and it has errors. I was wondering if there is any requirement to the video? such as resolution?

Did you find any solutions?

**Comment by kevinu0628** [comment]
I am implementing your codebase using frames cropped from teaser.mp4, but encountered technical obstacles during the first step in run.sh. 
(base) lfl@ubun:~/lfl_dev/hair_research/GaussianHaircut$ bash run_reconstruction_cmd.sh 
Optimizing /home/lfl/lfl_dev/hair_research/GaussianHaircut/data/3d_gaussian_splatting/stage1
Output folder: /home/lfl/lfl_dev/hair_research/GaussianHaircut/data/3d_gaussian_splatting/stage1 [14/03 13:40:58]
Reading camera 401/401 [14/03 13:40:59]
Loading Training Cameras [14/03 13:40:59]
100%|████████████████████████████████████████████████████████████████████████████| 128/128 [00:02<00:00, 55.61it/s]
Loading Test Cameras [14/03 13:41:01]
0it [00:00, ?it/s]
Number of points at initialisation :  78063 [14/03 13:41:01]
Training progress:   0%|                                                                 | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/lfl/lfl_dev/hair_research/GaussianHaircut/src/train_gaussians.py", line 321, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/home/lfl/lfl_dev/hair_research/GaussianHaircut/src/train_gaussians.py", line 110, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background)
  File "/home/lfl/lfl_dev/hair_research/GaussianHaircut/src/gaussian_renderer/__init__.py", line 106, in render
    radii[points_mask] = _radii
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.To ensure reproducibility, would you consider releasing the canonical demo dataset?

Your guidance would be greatly appreciated.Looking forward to your reply.
